config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  resources :cocktails, only: [ :index, :show, :new, :create ] do
    resources :doses, only: [ :new, :create, :destroy ]
  end
  resources :doses, only: [ :destroy ]
  root to: 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_attachment :photo
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, :cocktail, :ingredient, presence: true
  validates :ingredient, uniqueness: { scope: :cocktail }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [ :show ]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: [ :destroy ]
  before_action :set_cocktail, only: [ :new ]

  def new
    @dose = Dose.new
    @dose.cocktail = @cocktail
  end

  def create

    @dose = Dose.new(dose_params)
    if dose_params[:ingredient_id]
      @cocktail = Cocktail.find(params[:cocktail_id])
      @ingredient = Ingredient.find(dose_params[:ingredient_id])

      @dose.cocktail = @cocktail
      @dose.ingredient = @ingredient
    end
    @dose.valid?
    @dose.save

    redirect_to @cocktail, message: "olá"
  end

  def destroy
    @dose.destroy
    redirect_to cocktails_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def set_dose
    @dose = Dose.find(params[:id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/views/application/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to "Home", root_path, class: "navbar-wagon-brand" %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/cocktails/_form.html.erb
<div class="form-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <%= simple_form_for @cocktail do |f| %>
          <%= f.input :name %>
          <%= f.input :photo, as: :attachinary %>
          <%= f.button :submit %>
        <% end %>
        <%= link_to "Cancel", cocktails_path %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="container">
  <div class="wrapper">
    <div class="row">
      <% @cocktails.each do |c| %>
        <div class="col-xs-12 col-sm-4">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path c.photo.path, height: 333, width: 175, crop: :fit %>');">
            <div class="card-category">Cocktail</div>
            <div class="card-description">
              <h2>
                <%= link_to c.name, cocktail_path(c.id) %>
              </h2>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="wrapper">
    <div class="row">
      <div class="col-xs-12">
        <%= link_to "New Cocktail", new_cocktail_path, class: "btn btn-medium" %>
      </div>
    </div>
  </div>

</div>

app/views/cocktails/new.html.erb
<%= render 'form' %>

app/views/cocktails/show.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <h1><%= @cocktail.name %></h1>
    <% if @cocktail.photo? %>
      <%= cl_image_tag @cocktail.photo.path, width: 200, height: 300, crop: :fill %>
    <% end %>
    <ul>
      <% @cocktail.doses.each do |dose| %>
        <li>
          <%= dose.description %> of <%= dose.ingredient.name %>
          <%= link_to "delete", dose_path(dose), method: :delete %>
        </li>
      <% end %>
    </ul>
    <%= simple_form_for [@cocktail, @dose] do |f| %>
    <% if @dose.errors.any? %>
      <% @dose.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    <% end %>
    <%= f.input :description, placeholder: "2 teanspoons" %>
    <%= f.input :ingredient_id, collection: Ingredient.all, prompt: "Choose one" %>
    <%= f.submit "Add dose", class: "btn btn-primary" %>
    <%= link_to 'Back', cocktails_path, class: "btn btn-primary"%>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width-device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </body>
</html>